# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Insen
tagline:          'Write, Code, Dream !'  
description:      'Write, Code, Dream, Travel, Play !'
url:              https://insen.github.io/blog
baseurl:          https://insen.github.io/blog/

author:
  name:           insen
  url:            https://linkedin.com/nilsengupta

paginate:         5

# Custom vars
version:          1.0.0

connect:
  github:          https://github.com/insen
  linkedin:        https://www.linkedin.com/in/nilsengupta/

exclude:
  - docs\
  - .gitignore
  - .git
  - pbake.bat
  - ptaste.bat
  